import helper_functions as AFA
import resources as rsrc
import student_response_repo as SRR

subject = "History"
level = "Secondary 4"
question = " "
student_response = SRR.Pri_EL_Essay_3
#student_response = "There was too much glucose in the blood after consumption of breakfast, causing islets of Langerhans to be produced by the pancreas that secrete insulin. The liver then converts glucose into glucagon for storage and the blood glucose level decreases."
#student_response = "The Nazi government began rearmament in 1933 though it was banned under the Treaty of Versaille. Unemployed workers were selected into the army to build up its armed forces in secret. By 1935, Hitler did not hide the rearmament programme and held a freedom to Rearm rally in Berlin. Britain and France concerns grew over Germany’s military buildup, however, both countries did not want to get involved in another war so there was a policy of appeasement and they gave in to Hitler. This made Hitler think that both countries will always give in to him so he became bolder and wanted more. The both countries realised that Hitler would want more even if they gave in to him so they declared war with Germany."
#student_response2 = "The rearmament of Germany directly contributed to the outbreak of World War II by fuelling Hitler’s aggressive foreign policy and undermining the Treaty of Versailles. Hitler began secretly rearming Germany in 1933, expanding the military beyond the treaty’s limits. By 1935, this programme became public at the Freedom to Rearm Rally, where Hitler openly defied international restrictions. Rearmament not only bolstered Germany’s military power but also revitalised its economy by creating jobs, fostering public support for Hitler’s leadership. This emboldened him to militarise the Rhineland in 1936, directly violating the Treaty of Versailles and the Locarno Pact. Britain and France chose not to intervene, reinforcing Hitler’s belief that his aggressive policies would not face resistance.  Rearmament laid the foundation for Germany’s expansionist ambitions. With a stronger military, Hitler pursued aggressive policies such as the Anschluss with Austria in 1938 and the invasion of Poland in 1939, leading directly to war. Rearmament not only strengthened Germany’s capacity for war but encouraged Hitler to continue pushing boundaries unchecked. Germany’s rearmament was pivotal in fuelling Hitler’s aggressive policies, making war inevitable as diplomatic efforts to contain him consistently failed."
#student_response3 = "The rearmament of Germany directly contributed to the outbreak of World War II by fuelling Hitler’s aggressive foreign policy and undermining the Treaty of Versailles. Hitler began secretly rearming Germany in 1933, expanding the military beyond the treaty’s limits. By 1935, this programme became public at the Freedom to Rearm Rally, where Hitler openly defied international restrictions. Rearmament not only bolstered Germany’s military power but also revitalised its economy by creating jobs, fostering public support for Hitler’s leadership. This emboldened him to militarise the Rhineland in 1936, directly violating the Treaty of Versailles and the Locarno Pact. Britain and France chose not to intervene, reinforcing Hitler’s belief that his aggressive policies would not face resistance.  Rearmament laid the foundation for Germany’s expansionist ambitions. With a stronger military, Hitler pursued aggressive policies such as the Anschluss with Austria in 1938 and the invasion of Poland in 1939, leading directly to war. Rearmament not only strengthened Germany’s capacity for war but encouraged Hitler to continue pushing boundaries unchecked. Germany’s rearmament was pivotal in fuelling Hitler’s aggressive policies, making war inevitable as diplomatic efforts to contain him consistently failed. The ineffectiveness of the League of Nations and the policy of appeasement further contributed to the outbreak of World War II by failing to curb Hitler’s ambitions. The League of Nations was intended to prevent conflict through collective security but proved powerless during the 1930s. It failed to respond effectively to Japan’s invasion of Manchuria (1931) and Italy’s invasion of Abyssinia (1935), demonstrating its weakness. When Germany rearmed and militarised the Rhineland in 1936, the League took no significant action. Britain and France, preferring appeasement, allowed Hitler to annex Austria and the Sudetenland in 1938 without consequence. This emboldened Hitler, leading him to believe that further aggression would not be challenged. The League’s inability to enforce sanctions or mobilise military action encouraged aggressive expansion by authoritarian states. Hitler exploited this weakness, pushing his foreign policy goals with little fear of retribution. Appeasement delayed conflict but ultimately enabled Hitler to grow stronger, culminating in Germany’s invasion of Poland in 1939, which triggered the war. The failure of the League and appeasement revealed the lack of collective will to stop Hitler, allowing German aggression to spiral into global conflict."
error_tags = rsrc.ELLB_20
rubrics="Essay - Level 1 - did not list any factor and out of point, Essay - Level 2 - States 1 factor such as the violation of Treaty of Versailles, militarisation of Rhineland or Annexation of Anschluss, Essay - Level 3 - Provides 1 factor with explanation, Essay - Level 4 - Provides 2 factor with explanation, Essay - Level 5 - Provides 2 factors with explanation and evaluates the impact of each factor."
#pri_rubrics="Ideas - 1 - A slight attempt at developing ideas, Ideas - 2 - Ideas are generally developed, Ideas - 3 - Ideas are sufficiently developed, Ideas - 4 - Ideas are well-developed, Organisation - 1 - A slight attempt at organisation, Organisation - 2 - Some instances of organisation, Organisation - 3 - Good organisation, Organisation - 4 - Very good organisation, Voice - 1 - Shows slight awareness of purpose of writing, audience, and points of view, Voice - 2 - Shows some awareness of purpose of writing, audience, and points of view, Voice - 3 - Clear awareness of purpose of writing, audience, and points of view, Voice - 4 - Strong awareness of purpose of writing, audience, and points of view, Word Choice - 1 - Simple word choice, Word Choice - 2 - Fairly adequate word choice, Word Choice - 3 - Adequate word choice, Word Choice - 4 - Effective word choice, Sentence Fluency - 1 - Simple sentence fluency, Sentence Fluency - 2 - Attempts to use a variety of sentence structures, Sentence Fluency - 3 - Uses a variety of sentence structures, Sentence Fluency - 4 - Smooth flow of ideas with a variety of sentence structures."
#suggested_answer = "(1 mark): At 9am, the concentration of glucose in the blood was high, causing the islets of Langerhans to secrete insulin. (1 mark): Insulin stimulates the liver to convert excess glucose into glycogen, (1 mark): causing the blood glucose level to decrease."
recipe = " "

user_msg = AFA.assemble_prompt(subject, level, question, student_response, recipe=recipe, error_tags=error_tags, rubrics=" ", suggested_answer=" ")
response = AFA.get_annotations(user_msg)
print(response)
AFA.display_output(response)