Pri_EL_Essay_1 = """
"See you tommorow!" My teacher, Ms Lim exclaimed. Everyone rushed out of the classroom like a herd of Elephants. "La, la, la" I hummed a tune merrily as I walked back home. It was a seemingly peaceful afternoon. When came home, I was greated with an aroma of delicious food. After gobbling up my food, I immediately started reading a new book I got for my birthday. "Yes! I think I got to the interesting part." I thought. Right when I turned the page, I saw it marred with crayon scribbles! I knew my younger brother did it because he just got a new set of crayons. My face turned as red as any ku Kueh. I was furious! I stormmed into my brothers room and bellowed "WHAT DID YOU DO TO MY BOOK!" My brother hung his head in shame and muttered " I... I... am sorry" At that momment I could not control my emotions so I took his favourite Stuffed toy and ripped the head off. "That is what you get for ruining my book!" I said angryly. My brother burst out crying. I realised what I did and thought, "I have to fix this or else mom will scold me." I immediately ran to my friend's house, like a crazy mad horse on steroids. You may be thinking, why would I go to my friend, Amy? Well Amy is very good at sewing so, I wanted her to sew the head of the Stuffed toy back together with the body. "Ding! Dong!" I ringed the bell. When amy opened the door, I said, "hI Amy, I need you to help me sew this stuffed toy back together as fast as possible." She immediately took the toy and started sewing. I could not believe my eyes, she was so fast. After five minutes, everything was fixed. I thanked Amy profusely. She offered me to stay a bit longer but I really had to go back home. "See you at school!" Amy said. I came home panting, I was drenched in sweat. I realised that my mother was comforting my brother. When I walked into the room, I apologised. "I am so sorry for not controlling my emotions, I went out to ask Amy to sew it back together." My brother was very appy and jumped up and down. In a nutshell My mother was very Proud of me that I took responsibility to fix it back. The next time something like this happends, I will control my emotions. I was quite happy too, even though a page of my book was ruined and I did not control my emotions, I practiced to be responsible and I dit not get scolded by my mother.
"""
Pri_EL_Essay_2 = """
Annoyed and angry. That was what I felt before learning that my best friend had an accident and was in the hospital. "Finally! Today is the day to meet up with Parker!" I shouted with joy as I beamed from ear to ear. Parker and I were bossom buddies. We have been through thick and thin together and were as close as a hand and a glove. Our bond was unbreakable, until Parker had to leave and go to America. We both had set a date to meet up a few months later. His family was coming back to France, and so was he! We agreed to meet up at my parents restaurant. However, I had a long wait. Parker Bruno was late. He was never late, he was the most puntural person I knew. I then decided to call him after an hour. But he did not pick up, so I gave him a voice mail. "Parker! Where in the world are you? I have waited for an hour but you never appeared! Please don't tell me that you had forgotten our promise and bailed!" I said with anger boiling in me, as I drank my drink and sat at the table. Just then, Parker's mother called. "Michael!" she said. Mrs Bruno was crying. "Michael! Parker is in the hospital, he had an accident on the way to your familys restaurant," she sobbed. I stood rooted to the ground, shocked. My anger dispersed quickly as I pry the details from Mrs Bruno. "What! Parker was in an accident? Oh, I told him to be careful as he was driving in the wee hours! Which hospital is he in? I will go there now," I said. "He is at the France International Hospital." Mrs Bruno said. Without a second thought, I got into my car and rushed to the hospital. As I got out of my car, I saw Mrs Bruno waiting outside. We both quickly went up to Parker's ward. As I opened the door, strings of confetti rained on me. I was in utter shock! There stood Parker, all safe and sound. "Parker! I thought you were in an accident!" I shouted, clearly annoyed. "Hello to you to Michael. I was not, however, in an accident. Do you remember our promise that we made?" Parker said with a sly smile. Just then, it all dawned to me when I recalled. "Michael! Lets make a promise. After a few months, we will meet up and I promised you that you will chase after me!" Parker, a few months ago said. Tears blurred my vision as I send him of at the airport. Until now, he is still as sly as a fox. I smiled adoringly and gathered him into a hug. "I missed you," I said lovingly. "I miss you to," he replied. That long wait I had to experience was worth it. Today is 20th of July that I will remember forever.
"""
Pri_EL_Essay_3 = """
"Keep calm and love homework."-Anonymous. Homework is an essential tool in our lives, and many people get pressured and stressed by the overload of homework that they receive from their teachers over days some even going to the extent of crying. Homework was invented in 1905 by Robert Nevilin and is still very much present in today's modern schools. In my opinion, homework can be very useful to us and I do not agree with this statement. Many people complain that homework is useless. To begin with, homework is useful as it helps students learn to manage their time properly. Homework allows students to plan their time, so that they have sufficient time to study, do their homework, and also for leisure. The students will be able to learn how to put their homework as their first priority so that in the future, when they are working, they will be efficient and fast. However, there are also downsides to having homework. One may feel too stressed from keeping up deadlines and may not be able to cope with the enormous stress that they gain from it. Furthermore, homework can also help to improve one's grades, it can motivate students to continue studying and may even teach them a thing or two. In 2020, a research was conducted by Oxford University. They found out that 95% of students who consistently do their homework, do extraordinarily well in grades compared to students who are lazy and refuse to do their homework. In addition, homework also is a good way for revision. You can refer to it anytime you want one it has been marked and if there is any questions that needs to be clarified or, one may get wrong they can always ask the teacher how to solve the problem. Whatever homework students may not be able to do well in their studies and might not be motivated for school. Finally, homework is not a waste of time as without homework, many people will not be able to check if they are doing well in their studies or not. Homework helps to improve one's knowledge on the topic that they are doing and allows one to get better at it. If they are getting all the questions in the homework wrong, they will know which areas require improvements. From doing this, their grades will also improve and the students will be scoring higher marks compared to the homework as did not exist. Many people make the argument that people will have to sleep late if there is homework. However, if one has enough discipline and integrity, they will be able to finish their homework in time and be able to sleep early. In conclusion, homework is not a waste of time and it is very essential and useful in a student's life. Without it, many students may not be able to cope with their studies and eventually, their grades will dwindle.
"""
Pri_EL_Essay_4 = """
One day, Jake and his dad were driving to the store. It was a normal afternoon, and the road was not too busy. Jake was looking out the window when, suddenly, a loud crash shook the car.
A red truck had run a stop sign and hit their car from the side. Jake felt a strong jolt, and his seatbelt held him back. His dad quickly turned the wheel to stop the car from going off the road. The car came to a stop, and Jake's heart was beating fast.
His dad asked, “Are you okay?” Jake nodded, but he was scared. People from other cars ran over to help. The driver of the red truck got out and said, “I'm so sorry! I didn't see the sign.”
Soon, a police officer and an ambulance arrived. The paramedics checked Jake and his dad, but they were not hurt. The officer talked to the truck driver and wrote things down.
Jake's dad called a tow truck. “Cars can be fixed,” he said. “What matters is that we're safe.”
Jake looked at the dented car and took a deep breath. It had been a scary day, but he was glad they were okay.
"""

Pri_EL_Essay_5 = """
Many children seem to be glued to their phones, without having a time limit. They normally use their phones in the night, which causes to sleep late. Phones can be very addictive as there is games, and even youtube, just to let children enjoy their time. This causes them to be unable to focus in class, as they will not have enough sleep. hence, parents should actually put a limit to their children's time on electronic devices. Firstly, using all these electronic devices without any time limit will lead to any of the children's eyesight to spoil. When using too much electronic devices, like phones and tabllets, the chances of the eyes getting spoilt is quite high, as the brightness level is normally hugh, and children like to put the phones and tablets at leat just 15 cm awaty only, and that is not so far. If the brightness level is high, it is very risky. Hence, when children do niot have a time limit for using their electronic device, they will uncotrollably use their device, until their eyesight power will slowly worsen. Secondly, students wont be able to focus in class well, which will cause them to lack information that is teached in class. This is because they will not have enough sleep, due to them spending much time on their phones at night. Normally, children who dont feel tired at night, will use their phone until late night, and when they see the time, they become suprised as it would become too late, after they watch youtube and play games. Hence, without the time limit, the children will use their phone till they do not have enoough sleep, Lastly, children in future will not be focusing more on the amount of sleep they get, as they will get used to the the huge amount of time they use on their electronic device. In future, children might continue to sleep late, and lack the amount of sleep needed, which will lead to failure in future. Hence, it is better for parents to put a time limit to the usage of electronic devices for their children. Overall, parents should take control in terms of the time their children use on electronic devices. If parents do not make the right move now, in future their kids are just going to be letting their eyesihght to get worser, and lack sleep. This might also cause health problem in future.
"""
Pri_EL_Essay_6 = """
I used to think that hard work was not necessary and that I could always take shortcuts to achieve my goals. However, one incident changed my mindset forever, teaching me a valuable lesson about perseverance and responsibility.

It all started when my teacher announced that there would be a class mathematics competition. The winner would receive a trophy and a gift voucher. I was thrilled because I had always wanted to be recognised for my achievements. However, instead of practising diligently, I assumed that my natural ability would be enough to win. I only skimmed through a few questions the night before and went to bed early, confident that I would do well.

The next day, I walked into the classroom feeling excited. The competition began, and I was given a set of challenging math problems. As I stared at the questions, my confidence quickly faded. My mind went blank. I realised that I had no idea how to solve most of them. My hands grew clammy, and my heart pounded. I glanced around and saw my classmates deep in thought, solving the problems with ease. At that moment, regret filled me. If only I had prepared properly!

When the results were announced, I did not even make it to the top five. My face burned with embarrassment as my teacher handed the trophy to my best friend, Jason. He had worked tirelessly every day, revising and practising different types of questions. I felt a pang of guilt, knowing that I had taken the competition too lightly.

After school, I congratulated Jason and admitted that I had not put in enough effort. He smiled and said, “Hard work always pays off. You can do better next time if you really try.” His words stuck with me. That day, I made a promise to myself—to never take shortcuts again and to always put in my best effort.

Since then, I have learned the importance of perseverance and responsibility. Success does not come easily; it requires dedication and effort. That competition was a turning point in my life, and I will never forget the lesson it taught me.
"""
Pri_EL_Essay_7 ="""
Guilt weighed heavily on me as I replayed the argument in my mind. It had all started with a simple misunderstanding, but it had caused a rift between me and my best friend.

Jake and I had been inseparable since childhood. We did everything together, from playing video games and riding our bicycles around the neighbourhood to staying up late talking about life. He was the one person I could always count on, and I never thought anything could come between us. But one day, something happened that made me question our friendship.

I was walking past the school canteen when I heard laughter coming from a group of students. As I got closer, I recognised Jake’s voice among them. My heart sank when I heard my name being mentioned, followed by more laughter. My stomach twisted. Was he making fun of me? Was he telling jokes at my expense? A surge of anger and betrayal coursed through me.

Without waiting to hear more, I turned on my heel and walked away, my mind spinning. I felt humiliated and hurt. How could he, my best friend, talk about me behind my back? That evening, I could not shake the bitterness that filled me. The next day, I confronted him, my emotions bubbling over like a volcano about to erupt.

“How could you do that to me?” I snapped, my hands clenched into fists.

Jake looked confused. “What are you talking about?”

“Don’t play dumb! I heard you laughing about me with your new friends,” I accused, my voice rising.

His expression changed from confusion to hurt. “I wasn’t making fun of you,” he said, his tone defensive.

But I wasn’t in the mood to listen. Without giving him a chance to explain, I stormed off. Over the next few days, I ignored him completely. I avoided him in class, refused to respond to his texts, and even turned away when he tried to talk to me. I convinced myself that I was right to be angry.

It wasn’t until a few days later that I spoke to another friend about what had happened. He looked surprised and told me that I had completely misunderstood the situation. “Jake wasn’t making fun of you,” he said. “He was actually sharing a funny memory about the time you two got lost during last year’s school camp. Everyone was laughing because it was such a ridiculous story, not because they were mocking you.”

A cold wave of realisation washed over me. I had let my anger cloud my judgment. Instead of talking to Jake and finding out the truth, I had assumed the worst and shut him out. I had hurt someone who had always stood by me.

That evening, I mustered the courage to call him. As the phone rang, my heart pounded. What if he was still upset? What if I had ruined our friendship beyond repair?

When Jake picked up, I took a deep breath. “Jake, I’m so sorry,” I said, my voice trembling. “I should’ve trusted you instead of assuming the worst. I realise now that I jumped to conclusions without even giving you a chance to explain.”

There was a pause, and then he let out a small chuckle. “I was wondering when you’d come to your senses,” he said. “I was pretty hurt, you know. But I forgive you. Next time, talk to me first before deciding I’m the bad guy.”

Relief flooded me. I had been lucky—Jake was a true friend, and he was willing to put this behind us. That day, I learned a valuable lesson about trust and communication. Never assume the worst without hearing the full story. Misunderstandings can break even the strongest friendships if we let emotions take control. From that moment on, I promised myself that I would always seek the truth before jumping to conclusions.
"""
Pri_EL_Essay_8 = """
The sun's brilliant rays illuminated the morning sky. Plumes of bluish white clounds floated in a tranquil procession. It was a bright and beautiful day. I was coming home from my last day of school. I was so excited and jumped around. The school holiday had started. My parents had not planned anything for the holiday. When I was at home, I heard my parents in the room talking about where to go for the school holiday. I was shocked to see my room filled with suitcase which was packed. I knew immediately we were leaving the house for a holiday. My parents told me that we were going to malaysia. My adrenaline started pumping when I heard them say it. My parents and I immediately packed up and boarded our bus to go to malaysia. When we were at the malaysia immigration. We saw about thousands of people queuing. My parents and I queued at the shortest lane but to make problem worst the officer who was checking the passport went for a breaktime. I knew it be long wait. After an hour, the line started moving. Slowly but surely we were getting closer to the counter but it suddenly stopped. My parents saw. the sign on the board and told me that the computer in the office had broken down. I was frustrated but waited patiently. After three hours, my parents and I had crossed the counter. After waiting for a long time in the queue, my parents and I had a rest and had our dinner. I heaved sigh of relief that we were not still stuck there for far too long. My parents and I continued our journey to malaysia. At malaysia there was a lot of queues my parents and I had waited for nearly an hour but we learned something. Always be patient as we will be there in no time.
"""

sec_sample_m1 = """
Homework is something most students dread and claim to be a waste of time and hence, this brought about many contrasting views towards homework being a waste of time. while some people think that homework is a waste of time, I think that home work is actually useful for students. Therefore, I disagree that homework is a waste of time.

Firstly, homework acts as a mini test or a revision of a topic you did. So although you might think that you learnt everything you need to learn in school, homework actually tests your  application skills. In other words, homework test how you can use what you have learnt to answer questions. Therefore, homeworks can act as a mini test not only to test your knowledge of the topic, but also to test how you answer the topic.  

Secondly, especially for subjects like mathematics, homework can also act as a practice . Mathematics is a subject that many require practice as the more you practice, the more you get to familiarise the question types that might be tested for an exam. In addition, you do not have to mark your  work yourself and if you are unsure of a question or got something wrong , the teacher would be able to go through the homework with the whole class. Thus, I think that homework can act as a practice for students.

Lastly, I think that homework works as good revision notes to refer to for example, with the past worksheets or homework you did, you can take note of the questions you got incorrect and memorise the corrections or how to avoid that mistake. Therefore, worksheets can work as a helpful last-minute revision tool.  

In a nutshell, homework is a very useful learning tool that can play a part in how well you do in an exam. Although only doing homework is not enough to secure your results, I hope that people would start taking homework more seriously as it could play a huge role in you doing well for your examinations.
"""

#student_response = "The Nazi government began rearmament in 1933 though it was banned under the Treaty of Versaille. Unemployed workers were selected into the army to build up its armed forces in secret. By 1935, Hitler did not hide the rearmament programme and held a freedom to Rearm rally in Berlin. Britain and France concerns grew over Germany’s military buildup, however, both countries did not want to get involved in another war so there was a policy of appeasement and they gave in to Hitler. This made Hitler think that both countries will always give in to him so he became bolder and wanted more. The both countries realised that Hitler would want more even if they gave in to him so they declared war with Germany."
#student_response2 = "The rearmament of Germany directly contributed to the outbreak of World War II by fuelling Hitler’s aggressive foreign policy and undermining the Treaty of Versailles. Hitler began secretly rearming Germany in 1933, expanding the military beyond the treaty’s limits. By 1935, this programme became public at the Freedom to Rearm Rally, where Hitler openly defied international restrictions. Rearmament not only bolstered Germany’s military power but also revitalised its economy by creating jobs, fostering public support for Hitler’s leadership. This emboldened him to militarise the Rhineland in 1936, directly violating the Treaty of Versailles and the Locarno Pact. Britain and France chose not to intervene, reinforcing Hitler’s belief that his aggressive policies would not face resistance.  Rearmament laid the foundation for Germany’s expansionist ambitions. With a stronger military, Hitler pursued aggressive policies such as the Anschluss with Austria in 1938 and the invasion of Poland in 1939, leading directly to war. Rearmament not only strengthened Germany’s capacity for war but encouraged Hitler to continue pushing boundaries unchecked. Germany’s rearmament was pivotal in fuelling Hitler’s aggressive policies, making war inevitable as diplomatic efforts to contain him consistently failed."
#student_response3 = "The rearmament of Germany directly contributed to the outbreak of World War II by fuelling Hitler’s aggressive foreign policy and undermining the Treaty of Versailles. Hitler began secretly rearming Germany in 1933, expanding the military beyond the treaty’s limits. By 1935, this programme became public at the Freedom to Rearm Rally, where Hitler openly defied international restrictions. Rearmament not only bolstered Germany’s military power but also revitalised its economy by creating jobs, fostering public support for Hitler’s leadership. This emboldened him to militarise the Rhineland in 1936, directly violating the Treaty of Versailles and the Locarno Pact. Britain and France chose not to intervene, reinforcing Hitler’s belief that his aggressive policies would not face resistance.  Rearmament laid the foundation for Germany’s expansionist ambitions. With a stronger military, Hitler pursued aggressive policies such as the Anschluss with Austria in 1938 and the invasion of Poland in 1939, leading directly to war. Rearmament not only strengthened Germany’s capacity for war but encouraged Hitler to continue pushing boundaries unchecked. Germany’s rearmament was pivotal in fuelling Hitler’s aggressive policies, making war inevitable as diplomatic efforts to contain him consistently failed. The ineffectiveness of the League of Nations and the policy of appeasement further contributed to the outbreak of World War II by failing to curb Hitler’s ambitions. The League of Nations was intended to prevent conflict through collective security but proved powerless during the 1930s. It failed to respond effectively to Japan’s invasion of Manchuria (1931) and Italy’s invasion of Abyssinia (1935), demonstrating its weakness. When Germany rearmed and militarised the Rhineland in 1936, the League took no significant action. Britain and France, preferring appeasement, allowed Hitler to annex Austria and the Sudetenland in 1938 without consequence. This emboldened Hitler, leading him to believe that further aggression would not be challenged. The League’s inability to enforce sanctions or mobilise military action encouraged aggressive expansion by authoritarian states. Hitler exploited this weakness, pushing his foreign policy goals with little fear of retribution. Appeasement delayed conflict but ultimately enabled Hitler to grow stronger, culminating in Germany’s invasion of Poland in 1939, which triggered the war. The failure of the League and appeasement revealed the lack of collective will to stop Hitler, allowing German aggression to spiral into global conflict."
#student_response = "There was too much glucose in the blood after consumption of breakfast, causing islets of Langerhans to be produced by the pancreas that secrete insulin. The liver then converts glucose into glucagon for storage and the blood glucose level decreases."

#feedback reference
#pri_rubrics="Ideas - 1 - A slight attempt at developing ideas, Ideas - 2 - Ideas are generally developed, Ideas - 3 - Ideas are sufficiently developed, Ideas - 4 - Ideas are well-developed, Organisation - 1 - A slight attempt at organisation, Organisation - 2 - Some instances of organisation, Organisation - 3 - Good organisation, Organisation - 4 - Very good organisation, Voice - 1 - Shows slight awareness of purpose of writing, audience, and points of view, Voice - 2 - Shows some awareness of purpose of writing, audience, and points of view, Voice - 3 - Clear awareness of purpose of writing, audience, and points of view, Voice - 4 - Strong awareness of purpose of writing, audience, and points of view, Word Choice - 1 - Simple word choice, Word Choice - 2 - Fairly adequate word choice, Word Choice - 3 - Adequate word choice, Word Choice - 4 - Effective word choice, Sentence Fluency - 1 - Simple sentence fluency, Sentence Fluency - 2 - Attempts to use a variety of sentence structures, Sentence Fluency - 3 - Uses a variety of sentence structures, Sentence Fluency - 4 - Smooth flow of ideas with a variety of sentence structures."
#suggested_answer = "(1 mark): At 9am, the concentration of glucose in the blood was high, causing the islets of Langerhans to secrete insulin. (1 mark): Insulin stimulates the liver to convert excess glucose into glycogen, (1 mark): causing the blood glucose level to decrease."
#rubrics="Essay - Level 1 - did not list any factor and out of point, Essay - Level 2 - States 1 factor such as the violation of Treaty of Versailles, militarisation of Rhineland or Annexation of Anschluss, Essay - Level 3 - Provides 1 factor with explanation, Essay - Level 4 - Provides 2 factor with explanation, Essay - Level 5 - Provides 2 factors with explanation and evaluates the impact of each factor."